### PR TITLE
Tms dev index view

### PR DESCRIPTION
**Pull request by tmikeschu**
Re: #6 

This integrates the mobile first view that @damwhit (thanks, David!) taught me how to do yesterday.

All tests are passing, and I had to modify the item creation in the test to be through a `:category_with_items` factory to fit the wireframe we have. Similarly, the index action for items gathers all the categories instead of items, and we get items through the categories. 

If we don't want to have the category banners, it will be a quick fix in the view and controller.

---
Some more general styling takeaways from my pairing with David:
1. Bootstrap the nav bar if we want the “hamburger” collapse icon on the right. (I love that it’s called hamburger)
2. Mobile first is about designing all your mobile views first, then adding media queries for when the screen is bigger than a mobile width.
3. Sass/scss is a really nice way to organize css.

### CODE REVIEW

**Comment by kheppenstall** [comment]
👍 🌮 Thanks for making the changes in the item test and items controller. Items index looks good!

**Comment by wlffann** [comment]
@tmikeschu I'm really happy with the suggestions you guys came up with. I think using sass will be really helpful, especially now that we have a color scheme and the starts of branding. 

Also, way to commit to haml! Let's do this! 

🍔 🍔 🍔

**Comment by akintner** [comment]
This addresses and will also close #15. 
I'm excited about HAML

**Comment by wlffann** [comment]
closes #15

**Comment by tmikeschu** [comment]
@akintner I will go through and fix the styling, then this should be good to go. All tests passing.

**Comment by akintner** [comment]
I'm going to merge this now, and we can mange the whitespace and other Hound violations later.

**Pull request merged**
