### PR TITLE
16 ak categories styling

### PR DESCRIPTION
**Pull request by akintner**
I think we can go ahead and merge this. I'll do all the color styling on a new branch. Sound alright? @kheppenstall @wlffann @tmikeschu

### CODE REVIEW

**Comment by tmikeschu** [comment]
@akintner can you make sure master is merged into this branch and re push your branch?

screen shot 2017-01-04 at 5 51 10 pm

**Comment by akintner** [comment]
Merged with master on this branch and re-submitted. No conflicts were present.

**Comment by tmikeschu** [comment]
Awesome! Thanks for setting up a solid styling foundation for this view.

After we merge this PR, I'm going to refactor the show.html.haml with a partial, and it should be all good.

**Comment by kheppenstall** [comment]
👍

**Pull request merged**
