### PR TITLE
Ak dev all the colors

### PR DESCRIPTION
**Pull request by akintner**
new colors are loaded
tiny bug on line 17 of categories show page is fixed
working on styling after I make and eat dinner

### CODE REVIEW

**Comment by akintner** [comment]
@kheppenstall @wlffann @tmikeschu 
This is ready for review by ya'll.

**Comment by tmikeschu** [comment]
@akintner I know I'm a broken record with this, but can you git this branch merged with the current master first? My branch views say this branch is 3 behind.

**Comment by tmikeschu** [comment]
@akintner I realize this would probably fine, but I think it's a nice extra safety check.

**Comment by akintner** [comment]
There were no conflicts, so it was super fast. It was all cart stuff.

**Pull request merged**
