### PR TITLE
Kh dev seed file

### LINKED ISSUE #28: Explore carrierwave gem for image hosting

### LINKED ISSUE #31: create seed file

### PR DESCRIPTION
**Pull request by kheppenstall**
-Create seeds.rb file with coffee and nuts categories. Each category has two items. Item descriptions are all six lines on a desktop browser. 
-Add CarrierWave gem for image management.
-Change database to include image instead of image_url (to stick with the CarrierWave conventions found [here](https://github.com/carrierwaveuploader/carrierwave))
-Update item.rb to use CarrierWave and its built-in methods.
-Add an images folder in the db directory to store images for our items.
-Add an images folder under spec/support to store the image for the item factory. 

Closes #28 
Closes #31 

Thanks for the review @wlffann @tmikeschu @akintner .

### CODE REVIEW

**Comment by kheppenstall** [comment]
We will need to rake db:migrate then rake db:test:prepare after pulling down.

**Comment by kheppenstall** [comment]
Hound issues all cleaned up.

**Comment by kheppenstall** [comment]
Ready for review.

**Comment by akintner** [comment]
looks good

**Comment by wlffann** [comment]
Those images look great! This will help with styling immensely.

**Comment by tmikeschu** [comment]
Nice work on the seed, @kheppenstall ! Styling on the go will be a lot easier now. Let's look into flex alignment for each item card so we can handle potentially variable item sizes.

**Pull request merged**
