### PR TITLE
Aw categories #30

### LINKED ISSUE #30: update category path for resources
we ultimately want this to be a resource and not a wild card

### PR DESCRIPTION
**Pull request by wlffann**
Closes #30 

This keeps the wild-card implementation for the category routes but formats for spaces in category names.

### CODE REVIEW

**Comment by kheppenstall** [comment]
@wlffann Looks good to me. I made one comment about route testing.

**Comment by wlffann** [comment]
@kheppenstall and I discussed his comment, and decided to wait to refactor this.

I also fixed hound complaints. Happy with merging this now!

**Comment by tmikeschu** [comment]
Nice use of the `as: "category"`! I need to do this with the card. Thanks for figuring this out.

**Comment by akintner** [comment]
looks good, I'm going to merge this

**Pull request merged**
